---
abstract: 'Build dists like MyCompany ATS team'
author:
  - 'My Company <support@mycompany.com>'
build_requires:
  File::ShareDir: '0'
  Path::Class: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.150005'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-MyCompany-ATS
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla: '4.3'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::Git: '0'
  Dist::Zilla::Plugin::ModuleBuildTiny: '0'
  Dist::Zilla::Plugin::NameFromDirectory: '0'
  Dist::Zilla::Plugin::OurPkgVersion: '0'
  Dist::Zilla::Plugin::Prereqs::FromCPANfile: '0'
  Dist::Zilla::Plugin::RunExtraTests: '0'
  Dist::Zilla::Plugin::Test::ChangesHasContent: '0'
  Dist::Zilla::Plugin::VersionFromModule: '0'
  Dist::Zilla::Role::PluginBundle::Config::Slicer: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  File::ShareDir::Tarball: '0'
  Test::File::ShareDir: '0'
version: '0.002'
